/** Listed in `/help`; keep in sync with the handlers that implement them. */
export const SHORTCUTS: [keys: string, action: string][] = [
  ['/', 'commands'],
  ['$', 'use a skill or MCP prompt'],
  ['@', 'mention a file or folder'],
  ['enter', 'send, or steer while working'],
  ['ctrl+q', 'send after the current turn'],
  ['shift+enter', 'new line'],
  ['up/down', 'prompt history'],
  ['esc', 'interrupt the turn'],
  ['esc esc', 'rewind to an earlier message'],
  ['shift+tab', 'switch mode'],
  ['ctrl+c', 'interrupt, clear, quit'],
  ['ctrl+o', 'expand all output'],
  ['ctrl+t', 'background tasks'],
  ['ctrl+b', 'send the running command to the background'],
  ['ctrl+g', 'worktrees on or off for new conversations'],
  ['wheel', 'scroll the conversation'],
  ['pgup/pgdn', 'scroll by page'],
  ['drag', 'select text and copy it'],
  ['shift+drag', "the terminal's own selection"],
  ['ctrl+a/e', 'line start/end'],
  ['alt+left/right', 'move by word'],
  ['ctrl+w', 'delete word'],
  ['ctrl+u/k', 'delete to start/end'],
];
